Fix/help
cardeons/backend pull request #150
Opened 2021-04-15 08:42 UTC by Schoesswendter

2021-04-15 09:55 UTC, Moarales commented on app/channels/game_channel.rb
> +        PlayerChannel.broadcast_to(helping_player.user, { type: 'HANDCARD_UPDATE', params: { handcards: Gameboard.render_cards_array(helping_player.handcard.ingamedecks) } })
i hab gwusst wir haben des nu irgendwo gehabt mit da player id speichern, hab voi vergessen dass des da helping player is.... is dawei schätz i ok aber vl sollt ma des auch auf des player object ändern

2021-04-15 09:56 UTC, Moarales approved these changes
Haben wir für die Sachen scho Tests?, ansunsten nicer fix!

2021-04-15 12:52 UTC, Moarales requested changes

2021-04-15 12:52 UTC, Moarales commented on public/gamestates.md
> +      helping_player_atk: int,
isses immer 0 oder kanns a nil sein?
also haben wir einen default wert gesetzt bzw dass es nich nil sein darf?

2021-04-15 12:52 UTC, Moarales commented on public/gamestates.md
>        shared_reward: int,
isses immer 0 oder kanns a nil sein?

2021-04-19 13:03 UTC, dottolodaniela approved these changes

2021-04-19 13:04 UTC, merged