Feature/bossmonster
cardeons/backend pull request #174
Opened 2021-05-03 15:53 UTC by dottolodaniela

2021-05-03 17:16 UTC, Schoesswendter submitted a review, later dismissed

2021-05-03 17:28 UTC, Moarales requested changes

2021-05-03 17:28 UTC, Moarales commented on app/channels/game_channel.rb
> +        player = Player.find_by('user_id = ?', current_user.id)
shouldn't current_user.player do the same thing?

2021-05-03 17:28 UTC, Moarales commented on app/channels/game_channel.rb
> +    if @gameboard.intercept_phase? || @gameboard.boss_phase?
eher a early return mit einer error message, feedback is für die spieler und zum debuggen praktisch:
``` ruby
if !@gameboard.intercept_phase? && !@gameboard.boss_phase?
      PlayerChannel.broadcast_error(current_user, 'You cannot itnercept now, it is #{@gameboard.phase} phase')
     return
end
```

2021-05-03 17:28 UTC, Moarales commented on app/channels/game_channel.rb
> +    # centercard
# centercard ?

2021-05-03 17:28 UTC, Moarales commented on app/models/gameboard.rb
> +require 'pp'
muss ma ned importen [link](https://bigbinary.com/blog/ruby-2-5-requires-pp-by-default)

2021-05-03 17:28 UTC, Moarales commented on app/models/monstercard.rb
> +      # pp monsterslot.cards.where(type: 'Monstercard')
remove

2021-05-03 17:28 UTC, Moarales commented on app/models/gameboard.rb
> +  def self.attack(gameboard, curse_log = false, boss_phase = false)
is a param necessary?,

should we check this in this method?

2021-05-03 17:28 UTC, Moarales commented on app/models/monstercard.rb
> +      # player = gameboard.current_player
gewollt auskommentiert?

2021-05-03 17:28 UTC, Moarales commented on app/models/monstercard.rb
> +        player.update(level: player.level - 1) unless player.level == 1
player.decrement!(level, by = 1)

2021-05-04 13:03 UTC, Moarales requested changes

2021-05-05 07:04 UTC, Moarales approved these changes

2021-05-05 15:54 UTC, merged