Fix/pot of greed
cardeons/backend pull request #177
Opened 2021-05-04 14:13 UTC by dottolodaniela

2021-05-04 15:17 UTC, Moarales requested changes

2021-05-04 15:17 UTC, Moarales commented on db/seeds.rb
> -
do not change order of cards

2021-05-04 17:36 UTC, dottolodaniela commented on db/seeds.rb
> -
yes sir

2021-05-04 18:04 UTC, Schoesswendter approved these changes

2021-05-05 07:02 UTC, Moarales approved these changes

2021-05-05 09:50 UTC, merged